# Site settings
title: Event grid
email:
description: > # this means to ignore newlines until "baseurl:"
  Event web site
baseurl: "" # the subpath of your site, e.g. /blog/
url: 
twitter_username: username
github_username: username

