# Site settings
title: Hear Cape Town
email:
description: > # this means to ignore newlines until "baseurl:"
  hEAR web site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hearcapetown.co.za" # the base hostname & protocol for your site
twitter_username: username
github_username: username

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]