# Site settings
title: Event web site
email:
description: > # this means to ignore newlines until "baseurl:"
  Event web site
baseurl: "" # the subpath of your site, e.g. /blog/
url: 

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Event web site
author:
  name: Justin Slack
  email: justin@justinslack.com
# -----
# Build

include: ["_pages", "_header"]

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-autoprefixer

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

autoprefixer:
  browsers:
  - last 1 version

sass:
  style: compressed
  sourcemap: always

collections:
  speaker:
    title: Speaker
    permalink: /:collection/:path/
    output: true
  schedule:
    title: Schedule
    permalink: /:collection/:path/
    output: true
  
  